[theme]
base = "dark"
primaryColor = "#c7f36b"
backgroundColor = "#080b10"
secondaryBackgroundColor = "#131a24"
textColor = "#f4f7fb"
font = "sans serif"

[client]
toolbarMode = "viewer"

[server]
headless = true
